# Generated by Django 4.2.5 on 2023-09-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.CharField(max_length=100, verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображеие')),
                ('creation_date', models.TimeField(auto_now_add=True, verbose_name='дата создания')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('sign_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('views_count', models.IntegerField(default=0, verbose_name='просмотры')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
