# Generated by Django 4.2.5 on 2023-09-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='service.client', verbose_name='подписчики'),
        ),
    ]
