# Generated by Django 4.2.4 on 2023-08-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='client',
            field=models.ManyToManyField(to='service.client', verbose_name='Клиенты'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='service.message', verbose_name='Письма'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('daily', 'ежедневно'), ('weekly', 'еженедельно'), ('monthly', 'ежемесячно')], default='daily', max_length=10, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('completed', 'завершено'), ('created', 'создано'), ('commenced', 'запущено')], default='created', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
